ALTER TABLE `FAHRZEUG` CHANGE `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `FAHRZEUG` DROP `laufleistung`;
ALTER TABLE `FAHRZEUG_FARBE` CHANGE `NAME` `NAME` VARCHAR(20) NOT NULL;
ALTER TABLE `FAHRZEUG_KATEGORIE` CHANGE `NAME` `NAME` VARCHAR(20) NOT NULL;
ALTER TABLE `AUSSTATTUNG` CHANGE `ID` `ID` BIGINT(11) NOT NULL;
ALTER TABLE `BEWERTUNG` CHANGE `ID` `ID` BIGINT(11) NOT NULL;
ALTER TABLE `BUCHUNG` CHANGE `ID` `ID` BIGINT(11) NOT NULL;
ALTER TABLE `FAHRZEUG` CHANGE `ID` `ID` BIGINT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `FAHRZEUG_AUSSTATTUNG` CHANGE `ID` `ID` BIGINT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `FAHRZEUG_FARBE` CHANGE `ID` `ID` BIGINT(11) NOT NULL;
ALTER TABLE `FAHRZEUG_KATEGORIE` CHANGE `ID` `ID` BIGINT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `USER` CHANGE `ID` `ID` BIGINT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `FAHRZEUG` CHANGE `KM_STAND` `KM_STAND` VARCHAR(255) NOT NULL;
ALTER TABLE `FAHRZEUG` CHANGE `LEISTUNG` `LEISTUNG` VARCHAR(255) NOT NULL;
ALTER TABLE `FAHRZEUG` CHANGE `SITZPLAETZE` `SITZPLAETZE` VARCHAR(11) NULL DEFAULT NULL;
ALTER TABLE `USER` CHANGE `VERMIETER` `VERMIETER` BIT(11) NOT NULL;




ALTER TABLE `FAHRZEUG` CHANGE `EIGENTUEMER` `EIGENTUEMER` BIGINT NOT NULL;
ALTER TABLE `FAHRZEUG` CHANGE `KATEGORIE` `KATEGORIE` BIGINT NOT NULL;
ALTER TABLE `FAHRZEUG` CHANGE `HERSTELLER` `HERSTELLER` BIGINT NOT NULL;
ALTER TABLE `FAHRZEUG` CHANGE `FARBE` `FARBE` BIGINT NOT NULL;
ALTER TABLE `BUCHUNG` CHANGE `FAHRZEUG` `FAHRZEUG` BIGINT(11) NOT NULL;
ALTER TABLE `BUCHUNG` ADD FOREIGN KEY (`FAHRZEUG`) REFERENCES `FAHRZEUG`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `BUCHUNG` CHANGE `ID` `ID` BIGINT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `FAHRZEUG_AUSSTATTUNG` DROP `ID`;
ALTER TABLE `FAHRZEUG_AUSSTATTUNG` CHANGE `FAHRZEUG` `FAHRZEUG` BIGINT(11) NOT NULL;
ALTER TABLE `FAHRZEUG_AUSSTATTUNG` CHANGE `AUSSTATTUNG` `AUSSTATTUNG` BIGINT(11) NOT NULL;
ALTER TABLE `FAHRZEUG_AUSSTATTUNG` ADD FOREIGN KEY (`AUSSTATTUNG`) REFERENCES `AUSSTATTUNG`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `FAHRZEUG_AUSSTATTUNG` ADD FOREIGN KEY (`FAHRZEUG`) REFERENCES `FAHRZEUG`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;