ALTER TABLE `FAHRZEUG` CHANGE `MODELL` `MODELL` VARCHAR(20) NOT NULL;
ALTER TABLE `FAHRZEUG` CHANGE `sitzplaetze` `SITZPLAETZE` INT(11) NULL DEFAULT NULL;
ALTER TABLE `FAHRZEUG_HERSTELLER` CHANGE `NAME` `NAME` VARCHAR(20) NOT NULL;
ALTER TABLE `NUTZER` ADD `PASSWORD` VARCHAR(400) NOT NULL AFTER `VERMIETER`;
