<<<<<<< HEAD
ALTER TABLE `fahrzeug` ADD `KENNZEICHEN` VARCHAR(11) NOT NULL AFTER `ID`, 
ADD UNIQUE `KENNZEICHEN` (`KENNZEICHEN`);

ALTER TABLE `fahrzeug` CHANGE `KM_STAND` `LAUFLEISTUNG` INT(7) NOT NULL;
=======
ALTER TABLE `FAHRZEUG` ADD `EIGENTUEMER` INT(11) NOT NULL AFTER `PLZ`;
ALTER TABLE `FAHRZEUG` ADD FOREIGN KEY (`EIGENTUEMER`) REFERENCES `NUTZER`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
RENAME TABLE `carSharing`.`NUTZER` TO `carSharing`.`USER`;



>>>>>>> 7666aae2ae778dcd1c1805570cb25100dd83354a
