ALTER TABLE `FAHRZEUG` CHANGE `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `FAHRZEUG` DROP `laufleistung`;
ALTER TABLE `FAHRZEUG_FARBE` CHANGE `NAME` `NAME` VARCHAR(20) NOT NULL;
ALTER TABLE `FAHRZEUG_KATEGORIE` CHANGE `NAME` `NAME` VARCHAR(20) NOT NULL;