CREATE TABLE `carSharing`.`FAHRZEUG_MIETZEITRAUM` ( `ID` BIGINT NOT NULL AUTO_INCREMENT , `FAHRZEUG` BIGINT NOT NULL , `START_DATUM` DATE NOT NULL , `END_DATUM` DATE NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;

ALTER TABLE `FAHRZEUG_MIETZEITRAUM` ADD FOREIGN KEY (`FAHRZEUG`) REFERENCES `FAHRZEUG`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;