ALTER TABLE `BUCHUNG` DROP `nachricht`;
ALTER TABLE `BUCHUNG` ADD `TATSAECHLICHES_RUECKGABEDATUM` DATE NOT NULL AFTER `status`;
ALTER TABLE `BUCHUNG` CHANGE `TATSAECHLICHES_RUECKGABEDATUM` `TATSAECHLICHES_RUECKGABEDATUM` DATE NULL;